export const lightColorScheme = {
	'--ck-border-radius': '4px',
	'--ck-font-size-base': '14px',
	'--ck-custom-background': '',
	'--ck-custom-foreground': '',
	'--ck-custom-border': '',
	'--ck-custom-white': '',
	'--ck-color-base-foreground': '#fafafa',
	'--ck-color-focus-border': 'hsl(218,81.8%,56.9%)',
	'--ck-color-text': '#333',
	'--ck-color-shadow-drop': 'rgba(0,0,0,0.15)',
	'--ck-color-shadow-inner': 'rgba(0,0,0,0.1)',
	'--ck-color-button-default-background': 'transparent',
	'--ck-color-button-default-hover-background': '#f0f0f0',
	'--ck-color-button-default-active-background': '#f0f0f0',
	'--ck-color-button-default-active-shadow': '',
	'--ck-color-button-default-disabled-background': 'transparent',
	'--ck-color-button-on-background': '#f0f7ff',
	'--ck-color-button-on-hover-background': '#dbecff',
	'--ck-color-button-on-active-background': '#dbecff',
	'--ck-color-button-on-active-shadow': '',
	'--ck-color-button-on-disabled-background': '#f0f2f4',
	'--ck-color-button-action-background': '#53a336',
	'--ck-color-button-action-hover-background': '#4d9d30',
	'--ck-color-button-action-active-background': '#4d9d30',
	'--ck-color-button-action-active-shadow': '',
	'--ck-color-button-action-disabled-background': '#7ec365',
	'--ck-color-button-action-text': '#fff',
	'--ck-color-button-save': '#008a00',
	'--ck-color-button-cancel': '#db3700',
	'--ck-color-dropdown-panel-background': '#fff',
	'--ck-color-dropdown-panel-border': '#ccced1',
	'--ck-color-split-button-hover-background': '#ebebeb',
	'--ck-color-split-button-hover-border': '#b3b3b3',
	'--ck-color-input-background': '#fff',
	'--ck-color-input-border': '#ccced1',
	'--ck-color-input-text': '#333',
	'--ck-color-input-disabled-background': '#f2f2f2',
	'--ck-color-input-disabled-border': '#ccced1',
	'--ck-color-input-disabled-text': '#757575',
	'--ck-color-labeled-field-label-background': '#fff',
	'--ck-color-list-background': '#fff',
	'--ck-color-list-button-hover-background': '#f0f0f0',
	'--ck-color-list-button-on-background': '#2977ff',
	'--ck-color-list-button-on-background-focus': '#2977ff',
	'--ck-color-list-button-on-text': '#fff',
	'--ck-color-panel-background': '#fff',
	'--ck-color-panel-border': '#ccced1',
	'--ck-color-toolbar-background': '#fff',
	'--ck-color-toolbar-border': '#ccced1',
	'--ck-color-tooltip-background': '#333',
	'--ck-color-tooltip-text': '#fff',
	'--ck-color-image-caption-background': '#f7f7f7',
	'--ck-color-image-caption-text': '#333',
	'--ck-color-widget-blurred-border': '#dedede',
	'--ck-color-widget-hover-border': '#ffc83d',
	'--ck-color-widget-editable-focus-background': '#fff',
	'--ck-color-link-default': '#0000f0',
	'--ck-color-base-border': '#ccced1',
	'--ck-color-base-background': '#fff',
};

export const darkColorScheme = {
	'--ck-border-radius': '4px',
	'--ck-font-size-base': '14px',
	'--ck-custom-background': 'hsl(270, 1%, 29%)',
	'--ck-custom-foreground': 'hsl(255, 3%, 18%)',
	'--ck-custom-border': 'hsl(300, 1%, 22%)',
	'--ck-custom-white': 'hsl(0, 0%, 100%)',
	'--ck-color-base-foreground': 'var(--ck-custom-background)',
	'--ck-color-focus-border': 'hsl(208, 90%, 62%)',
	'--ck-color-text': 'hsl(0, 0%, 98%)',
	'--ck-color-shadow-drop': 'hsla(0, 0%, 0%, 0.2)',
	'--ck-color-shadow-inner': 'hsla(0, 0%, 0%, 0.1)',
	'--ck-color-button-default-background': 'var(--ck-custom-background)',
	'--ck-color-button-default-hover-background': 'hsl(270, 1%, 22%)',
	'--ck-color-button-default-active-background': 'hsl(270, 2%, 20%)',
	'--ck-color-button-default-active-shadow': 'hsl(270, 2%, 23%)',
	'--ck-color-button-default-disabled-background':
		'var(--ck-custom-background)',
	'--ck-color-button-on-background': 'var(--ck-custom-foreground)',
	'--ck-color-button-on-hover-background': 'hsl(255, 4%, 16%)',
	'--ck-color-button-on-active-background': 'hsl(255, 4%, 14%)',
	'--ck-color-button-on-active-shadow': 'hsl(240, 3%, 19%)',
	'--ck-color-button-on-disabled-background': 'var(--ck-custom-foreground)',
	'--ck-color-button-action-background': 'hsl(168, 76%, 42%)',
	'--ck-color-button-action-hover-background': 'hsl(168, 76%, 38%)',
	'--ck-color-button-action-active-background': 'hsl(168, 76%, 36%)',
	'--ck-color-button-action-active-shadow': 'hsl(168, 75%, 34%)',
	'--ck-color-button-action-disabled-background': 'hsl(168, 76%, 42%)',
	'--ck-color-button-action-text': 'var(--ck-custom-white)',
	'--ck-color-button-save': 'hsl(120, 100%, 46%)',
	'--ck-color-button-cancel': 'hsl(15, 100%, 56%)',
	'--ck-color-dropdown-panel-background': 'var(--ck-custom-background)',
	'--ck-color-dropdown-panel-border': 'var(--ck-custom-foreground)',
	'--ck-color-split-button-hover-background':
		'var(--ck-color-button-default-hover-background)',
	'--ck-color-split-button-hover-border': 'var(--ck-custom-foreground)',
	'--ck-color-input-background': 'var(--ck-custom-background)',
	'--ck-color-input-border': 'hsl(257, 3%, 43%)',
	'--ck-color-input-text': 'hsl(0, 0%, 98%)',
	'--ck-color-input-disabled-background': 'hsl(255, 4%, 21%)',
	'--ck-color-input-disabled-border': 'hsl(250, 3%, 38%)',
	'--ck-color-input-disabled-text': 'hsl(0, 0%, 78%)',
	'--ck-color-labeled-field-label-background': 'var(--ck-custom-background)',
	'--ck-color-list-background': 'var(--ck-custom-background)',
	'--ck-color-list-button-hover-background': 'var(--ck-color-base-foreground)',
	'--ck-color-list-button-on-background': 'var(--ck-color-base-active)',
	'--ck-color-list-button-on-background-focus':
		'var(--ck-color-base-active-focus)',
	'--ck-color-list-button-on-text': 'var(--ck-color-base-background)',
	'--ck-color-panel-background': 'var(--ck-custom-background)',
	'--ck-color-panel-border': 'var(--ck-custom-border)',
	'--ck-color-toolbar-background': 'var(--ck-custom-background)',
	'--ck-color-toolbar-border': 'var(--ck-custom-border)',
	'--ck-color-tooltip-background': 'hsl(252, 7%, 14%)',
	'--ck-color-tooltip-text': 'hsl(0, 0%, 93%)',
	'--ck-color-image-caption-background': 'hsl(0, 0%, 97%)',
	'--ck-color-image-caption-text': 'hsl(0, 0%, 20%)',
	'--ck-color-widget-blurred-border': 'hsl(0, 0%, 87%)',
	'--ck-color-widget-hover-border': 'hsl(43, 100%, 68%)',
	'--ck-color-widget-editable-focus-background': 'var(--ck-custom-white)',
	'--ck-color-link-default': 'hsl(190, 100%, 75%)',
	'--ck-color-base-border': '#373A40',
	'--ck-color-base-background': '#25262b',
};
